### ISSUE TITLE
Brew warning Warning: Calling bottle :unneeded is deprecated! There is no replacement.

### ISSUE THREAD

**Issue by tracure1337** [trashhalo/imgcat#19]
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the trashhalo/brews tap (not Homebrew/brew or Homebrew/core):
  /opt/homebrew/Library/Taps/trashhalo/homebrew-brews/Formula/imgcat.rb:6

**Comment by tmickleydoyle** [comment]
I am experiencing the same error. I think this [line](https://github.com/trashhalo/homebrew-brews/blob/main/Formula/imgcat.rb#L6) is not needed.

**Comment by tmickleydoyle** [comment]
Here is an example of a PR that resolved a similar issue: https://github.com/charmbracelet/homebrew-tap/pull/4/commits/c2ef9d84126f4d704a26504b7718c28fe08bfafc

**Comment by trashhalo** [comment]
deleted can you let me know if it works? https://github.com/trashhalo/homebrew-brews/commit/3bec8514393d6afe5b641f555a124eded43f9f51

**Comment by tmickleydoyle** [comment]
Works!!!

![Screen Shot 2022-03-03 at 1 20 01 PM](https://user-images.githubusercontent.com/8069675/156637281-34259aa6-e718-47a2-93ad-f35389181cb4.png)

**Comment by tmickleydoyle** [comment]
Thank you for the super quick turn around on this PR 🙇

**Comment by trashhalo** [comment]
no, thank you for submitting it! ❤️
