### ISSUE TITLE
Higher resolution by mixing fore- & background colors

### ISSUE THREAD

**Issue by muesli** [trashhalo/imgcat#3]
It would be interesting to achieve a higher display resolution by combining fore- & background colors on half-height blocks and graphic characters like:

```
▄▀
```

and

```
░▒▓
```

**Comment by trashhalo** [comment]
Dude it works. Just pushed a commit. Check out the difference it makes:

Before commit

![sample](https://user-images.githubusercontent.com/177491/97096466-c1301480-163a-11eb-9f1c-e9e8d7999c80.png)

After commit

![double](https://user-images.githubusercontent.com/177491/97096472-cbeaa980-163a-11eb-8f2d-d8147c1e1798.png)

**Comment by trashhalo** [comment]
THANK YOU FOR THE SUGGESTION. YOU ROCK

**Comment by muesli** [comment]
That's flippin' fantastic! :heart:

**Comment by muesli** [comment]
Super impressive, really! You should probably update the sample.png used in the README! :smiley:

**Comment by penguwin** [comment]
love it!

**Comment by boxed** [comment]
The after image is just the half height stuff and not the characters that could be used for dithering?

**Comment by muesli** [comment]
@boxed Correct!

**Comment by daleroberts** [comment]
You can take the concept even further, see https://github.com/daleroberts/tv
