### ISSUE TITLE
Support EXIF Orientation

### ISSUE THREAD

**Issue by jpillora** [trashhalo/imgcat#8]
I just ran `imgcat` on one of my photos and it appeared rotated 90 degrees. This rotation information is stored in EXIF metadata and could be counter-rotated before display.

With [vexif/main.go](https://github.com/jpillora/vexif/blob/master/main.go):

```
$ vexif mypic.JPG | grep Orientation
  Orientation = 6
```

https://jdhao.github.io/2019/07/31/image_rotation_exif_info/

**Comment by trashhalo** [comment]
Jpppgggsss!!!

Thanks for raising this. Ill look around for some go options for supporting rotations.

**Comment by trashhalo** [comment]
@jpillora Are you technically inclined? I pushed pull request up thats using a library to rotate the images correctly... but I dont have any imgs to test it with.

Would you try to use the version of imgcat on this branch to see if it works with your images? https://github.com/trashhalo/imgcat/pull/10

If you are unsure how to do that you could also email me one of your images with this issue solka@hey.com so I could test it before merging.

**Comment by jpillora** [comment]
Sent you a photo 👍

**Comment by trashhalo** [comment]
Thanks for the beautiful photo. Fix is in https://github.com/trashhalo/imgcat/releases/tag/v1.1.1

![](https://media.giphy.com/media/QN6NnhbgfOpoI/giphy.gif)

**Comment by jpillora** [comment]
Thanks 🙌
